# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EmailCli < Formula
  desc "A beautiful and functional email client for your terminal."
  homepage "https://github.com/andrinoff/email-cli"
  version "0.6.1"

  on_macos do
    on_intel do
      url "https://github.com/andrinoff/email-cli/releases/download/v0.6.1/email-cli_0.6.1_darwin_amd64.tar.gz"
      sha256 "ecf8555a60428f84e1fc045bdead160af4c1fb94413f9887d834699dd0c0ecb3"

      def install
        bin.install "email-cli"
      end
    end
    on_arm do
      url "https://github.com/andrinoff/email-cli/releases/download/v0.6.1/email-cli_0.6.1_darwin_arm64.tar.gz"
      sha256 "668ad2415e9b577a7babbe141c7cbe6eb3b104a45dd09aef7beca9d31b61343a"

      def install
        bin.install "email-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andrinoff/email-cli/releases/download/v0.6.1/email-cli_0.6.1_linux_amd64.tar.gz"
        sha256 "7a981f00dcf79c6fbc98c04d6f5c26e7bfcb33fb72fc38f1da1d44e6e392e333"

        def install
          bin.install "email-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andrinoff/email-cli/releases/download/v0.6.1/email-cli_0.6.1_linux_arm64.tar.gz"
        sha256 "e96be20e468bb9defebaa9f0483f295376ac049041cca6ff5f308748ac1e97b0"

        def install
          bin.install "email-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/email-cli --version"
  end
end
