# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EmailCli < Formula
  desc "A beautiful and functional email client for your terminal."
  homepage "https://github.com/andrinoff/email-cli"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/andrinoff/email-cli/releases/download/v0.0.1/email-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "d114f11d99b6b8662e7e457eab1d46b14c1523720a10d5ef5ec92f08229ed64b"

      def install
        bin.install "email-cli"
      end
    end
    on_arm do
      url "https://github.com/andrinoff/email-cli/releases/download/v0.0.1/email-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "a5c0dda57b9ab7c17ae35ac74ff018f980459aa272a0df89ad39c1d43a9d9900"

      def install
        bin.install "email-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andrinoff/email-cli/releases/download/v0.0.1/email-cli_0.0.1_linux_amd64.tar.gz"
        sha256 "f70a73ac55d5df49650b7d17e30f4c0438269b14920314950202e01740aaa13a"

        def install
          bin.install "email-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andrinoff/email-cli/releases/download/v0.0.1/email-cli_0.0.1_linux_arm64.tar.gz"
        sha256 "c715ca8c8d8db58ca08f21126c955ebca2e4cf5c5c59e05cf2228e92475c42b4"

        def install
          bin.install "email-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/email-cli --version"
  end
end
